version: '3'
services:
    isa-blog-db:
      image: mariadb:10.4.4
      container_name: isa-blog-db-dev
      restart: unless-stopped
      environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=blog
      command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default_time_zone=-03:00 --net-read-timeout=60 --net-write-timeout=120 --max-allowed-packet=536870912 --wait-timeout=1850 --interactive-timeout=1850
      networks:
        - isa-blog-backend-dev
      volumes:
        - mariadb-isa-blog:/var/lib/mysql

    isa-blog-backend:
      image: jhipster/jhipster
      container_name: isa-blog-backend-dev
      restart: unless-stopped
      depends_on:
        - isa-blog-db
      ports:
        - '8080:8080'
        - '9000:9000'
        - '3001:3001'
      networks:
        - isa-blog-backend-dev
      volumes:
        - ~/ingenieria-software-aplicada/blog:/home/jhipster/app
        - ~/ingenieria-software-aplicada/blog/.m2:/home/jhipster/.m2
        - ~/jdk-11.0.12+7:/home/jhipster/jdk-11.0.12+7

networks:
  isa-blog-backend-dev:
    driver: 'bridge'

volumes:
  mariadb-isa-blog:
